Skip wrong attach_enode in z3 4.8.7

diff --git a/.github/workflows/continuous_integration.yml b/.github/workflows/continuous_integration.yml
--- a/.github/workflows/continuous_integration.yml
+++ b/.github/workflows/continuous_integration.yml
@@ -109,7 +109,7 @@ jobs:
               rm -f "logs/${base_name}_fHash_*.log"
               echo "Processing $file to $log_file_name"
               # Run Z3 solver for the file and save the log in the 'logs' directory, TODO: `proof=true`?
-              z3 trace=true -T:60 trace-file-name=${log_file_name} ./$file > /dev/null || echo "!!! Error processing $file"
+              z3 trace=true -T:300 trace-file-name=${log_file_name} ./$file > /dev/null || echo "!!! Error processing $file"
           done
 
       # TODO: not enough permission for this.
