Update CI and add two new examples

diff --git a/.github/workflows/continuous_integration.yml b/.github/workflows/continuous_integration.yml
--- a/.github/workflows/continuous_integration.yml
+++ b/.github/workflows/continuous_integration.yml
@@ -29,21 +29,26 @@ jobs:
       fail-fast: false
       matrix:
         z3version: ['4.8.7', '4.8.17', '4.11.2', '4.12.2', '4.12.4']
-    # Use macOS runner since it has double the RAM of the other runners (14GB vs 7GB)
+    # Linux, Processor (CPU): 4, Memory (RAM): 16 GB, Storage (SSD): 14 GB
     # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
-    runs-on: macos-latest
+    runs-on: ubuntu-latest
 
     steps:
     - uses: actions/checkout@v4
     - id: configure-z3-id
       run: echo "z3_v_clean=$(echo "${{ matrix.z3version }}" | sed 's/\./_/g')" >> $GITHUB_OUTPUT
+    - name: Cache cargo
+      uses: Swatinem/rust-cache@v2
+      with:
+        shared-key: "shared"
     - uses: actions/cache/restore@v3
       with:
         path: logs
         key: logs-${{ steps.configure-z3-id.outputs.z3_v_clean }}-${{ hashFiles('smt-problems/**/*.smt2') }}
+        restore-keys: logs-${{ steps.configure-z3-id.outputs.z3_v_clean }}-
     - id: check-logs-cached
       run: ls -la logs
-    - run: SLP_MEMORY_LIMIT_GB=13 cargo test --workspace -- --nocapture
+    - run: SLP_MEMORY_LIMIT_GB=16 cargo test --workspace -- --nocapture
 
     # Failure
     - run: tar -czf failing_logs.tar.bz2 logs/
@@ -86,8 +91,11 @@ jobs:
 
       - name: Configure Z3 version environment variable
         id: configure-z3-id
-        run:
+        run: |
+          # Generate filename comaptible version: 4.8.7 -> 4_8_7
           echo "z3_v_clean=$(echo "${{ matrix.z3version }}" | sed 's/\./_/g')" >> $GITHUB_OUTPUT
+          # Generate regex compatible version: 4.8.7 -> 4\.8\.7
+          echo "z3_v_regex=$(echo "${{ matrix.z3version }}" | sed 's/\./\\./g')" >> $GITHUB_OUTPUT
 
       - name: Cache log files
         id: cache-log
@@ -95,8 +103,7 @@ jobs:
         with:
           path: logs
           key: logs-${{ steps.configure-z3-id.outputs.z3_v_clean }}-${{ hashFiles('smt-problems/**/*.smt2') }}
-          restore-keys: |
-            logs-${{ steps.configure-z3-id.outputs.z3_v_clean }}-
+          restore-keys: logs-${{ steps.configure-z3-id.outputs.z3_v_clean }}-
 
       - name: Run Z3 solver on changed smt2 files and compress
         id: run_z3_and_upload
@@ -107,18 +114,30 @@ jobs:
           # Loop through all files and check that log exists
           for file in smt-problems/**/*.smt2; do
               test -f "$file" || break
+              # Skip if the file if the first line is a comment with 
+              [ "$(sed -n '/^;[^\n]*${{ steps.configure-z3-id.outputs.z3_v_regex }}/p;q' $file)" ] && echo "Skipping $file since the first line contains \"${{ matrix.z3version }}\"" && continue || true
               # Get the file hash
               file_hash=$(shasum -a 256 "$file" | cut -d' ' -f1)
               # Get the filename without extension
               base_name=$(basename "${file%.*}")
               # Log file name
               log_file_name="logs/${base_name}_fHash_${file_hash}.log"
-              test -f "${log_file_name}" && continue
+              # Skip if log file exists and is not empty
+              test -s "${log_file_name}" && continue || true
 
               rm -f "logs/${base_name}_fHash_*.log"
-              echo "Processing $file to $log_file_name"
-              # Run Z3 solver for the file and save the log in the 'logs' directory, TODO: `proof=true`?
-              z3 trace=true -T:300 trace-file-name=${log_file_name} ./$file > /dev/null || echo "!!! Error processing $file"
+              echo "Processing \"$file\" to \"$log_file_name\""
+
+              # Run Z3 solver for the file and save the log in the 'logs' directory.
+              # The memory limit is set to 15.5GB and the timeout is set to 30 seconds
+              # (this limits the log file size to roughly <=4GB). We redirect
+              # the output so that it doesn't get printed and listen for a
+              # timeout message in which case we remove the last line of the log
+              # file since it may be incomplete (and cause parsing errors).
+              z3 trace=true proof=true -memory:15872 -T:10 trace-file-name=${log_file_name} ./$file \
+                 > >(grep -q "timeout" && echo "[Timeout] Removing last line of logfile" && tail -n 1 "${log_file_name}" | wc -c | xargs -I {} truncate -s -{} "${log_file_name}") \
+                  || echo "!!! Error processing \"$file\""
+              test -s "${log_file_name}" || echo "!!! Log file not created for \"$file\""
           done
 
       # TODO: not enough permission for this.
