Testing

diff --git a/.github/workflows/z3_trace_log_gen.yml b/.github/workflows/z3_trace_log_gen.yml
--- a/.github/workflows/z3_trace_log_gen.yml
+++ b/.github/workflows/z3_trace_log_gen.yml
@@ -73,20 +73,22 @@ jobs:
               # Run Z3 solver for the file and save the log in the 'logs' directory
               z3 trace=true proof=true trace-file-name=logs/${base_name}.log ./$file > /dev/null || echo "!!! Error processing $file"
           done
-          # Loop through all files and check that log exists
-          for file in smt-problems/**/*.smt2; do
-              test -f "$file" || break
-              # Get the filename without extension
-              base_name=$(basename "${file%.*}")
-              test -f "logs/${base_name}.log" && continue
+          # # Loop through all files and check that log exists
+          # for file in smt-problems/**/*.smt2; do
+          #     test -f "$file" || break
+          #     # Get the filename without extension
+          #     base_name=$(basename "${file%.*}")
+          #     test -f "logs/${base_name}.log" && continue
 
-              echo "Processing uncached $file"
-              # Run Z3 solver for the file and save the log in the 'logs' directory
-              z3 trace=true proof=true trace-file-name=logs/${base_name}.log ./$file > /dev/null || echo "!!! Error processing $file"
-          done
+          #     echo "Processing uncached $file"
+          #     # Run Z3 solver for the file and save the log in the 'logs' directory
+          #     z3 trace=true proof=true trace-file-name=logs/${base_name}.log ./$file > /dev/null || echo "!!! Error processing $file"
+          # done
 
           # Compress the 'logs' directory using bzip2
+          echo "Compressing to $cache-file"
           tar -cjf "$cache-file" logs/
+          ls -la
           echo "logs_path=$(realpath ${cache-file})" >> $GITHUB_OUTPUT
 
       - name: Delete old cache
