Do not fail if z3 segfaults, we should investigate this

diff --git a/.github/workflows/z3_trace_log_gen.yml b/.github/workflows/z3_trace_log_gen.yml
--- a/.github/workflows/z3_trace_log_gen.yml
+++ b/.github/workflows/z3_trace_log_gen.yml
@@ -71,7 +71,7 @@ jobs:
               # Get the filename without extension
               base_name=$(basename "${file%.*}")
               # Run Z3 solver for the file and save the log in the 'logs' directory
-              z3 trace=true proof=true trace-file-name=logs/${base_name}.log ./$file > /dev/null
+              z3 trace=true proof=true trace-file-name=logs/${base_name}.log ./$file > /dev/null || echo "!!! Error processing $file"
           done
           # Loop through all files and check that log exists
           for file in smt-problems/**/*.smt2; do
@@ -82,7 +82,7 @@ jobs:
 
               echo "Processing uncached $file"
               # Run Z3 solver for the file and save the log in the 'logs' directory
-              z3 trace=true proof=true trace-file-name=logs/${base_name}.log ./$file > /dev/null
+              z3 trace=true proof=true trace-file-name=logs/${base_name}.log ./$file > /dev/null || echo "!!! Error processing $file"
           done
 
           # Compress the 'logs' directory using bzip2
