Try saving z3 log files in cache

diff --git a/.github/workflows/z3_trace_log_gen.yml b/.github/workflows/z3_trace_log_gen.yml
--- a/.github/workflows/z3_trace_log_gen.yml
+++ b/.github/workflows/z3_trace_log_gen.yml
@@ -3,9 +3,6 @@ name: Z3 Trace Log Generator
 on:
   push:
     branches: [ "main" ]
-    # only triggers job when smt2 files are changed (added/removed/modified) in a push
-    paths:
-      - '**/smt-problems/*.smt2'
 
   # job can also be triggered manually on GitHub
   workflow_dispatch:
@@ -14,7 +11,7 @@ jobs:
   generate_log:
     strategy: 
       matrix:
-        z3version: ['4.12.2'] 
+        z3version: ['4.12.2']
     
     # for versions of Z3 at least 4.9.0 we need v1.3 of the GitHub action, for older versions of Z3, 1.2.2
     runs-on: ubuntu-latest
@@ -36,6 +33,20 @@ jobs:
         with:
           version: ${{ matrix.z3version }} 
 
+      - name: Configure Z3 version environment variable
+        id: configure-z3-id
+        run:
+          echo "z3_v_clean=$(echo "${{ matrix.z3version }}" | sed 's/\./_/g')" >> $GITHUB_OUTPUT
+
+      - name: Cache log files
+        id: cache-log
+        uses: actions/cache@v3
+        with:
+          path: logs_z3_v${{ steps.configure-z3-id.outputs.z3_v_clean }}.tar.bz2
+          key: logs-${{ steps.configure-z3-id.outputs.z3_v_clean }}-${{ github.sha }}
+          restore-keys: |
+            logs-${{ steps.configure-z3-id.outputs.z3_v_clean }}-
+
       # this fetches all changed (added/modified) smt2 files in the repository 
       - name: Fetch changed smt2 files
         id: changed-smt2-files
@@ -43,32 +54,53 @@ jobs:
         with: 
           files_yaml: |
             smt:
-              - '**/*.smt2'
+              - 'smt-problems/**/*.smt2'
 
       - name: Run Z3 solver on changed smt2 files and compress 
         id: run_z3_and_upload
+        env:
+          cache-file: logs_z3_v${{ steps.configure-z3-id.outputs.z3_v_clean }}.tar.bz2
         run: |
           # Create the 'logs' directory
           mkdir logs
+          test -f "$cache-file" && tar -xf "$cache-file" || echo "No cache"
 
-          # Loop through the files
+          # Loop through changed files
           for file in ${{ steps.changed-smt2-files.outputs.smt_all_changed_files }}; do
               echo "Processing $file"
-              
               # Get the filename without extension
               base_name=$(basename "${file%.*}")
-              
+              # Run Z3 solver for the file and save the log in the 'logs' directory
+              z3 trace=true proof=true trace-file-name=logs/${base_name}.log ./$file
+          done
+          # Loop through all files and check that log exists
+          for file in smt-problems/**/*.smt2; do
+              test -f "$file" || break
+              # Get the filename without extension
+              base_name=$(basename "${file%.*}")
+              test -f "logs/${base_name}.log" && continue
+
+              echo "Processing uncached $file"
               # Run Z3 solver for the file and save the log in the 'logs' directory
               z3 trace=true proof=true trace-file-name=logs/${base_name}.log ./$file
           done
 
           # Compress the 'logs' directory using bzip2
-          z3_v_clean=$(echo "${{ matrix.z3version }}" | sed 's/\./_/g')
-          tar -cjf logs_z3_v${z3_v_clean}.tar.bz2 logs/
-          echo "logs_path=$(realpath logs_z3_v${z3_v_clean}.tar.bz2)" >> $GITHUB_OUTPUT
+          tar -cjf "$cache-file" logs/
+          echo "logs_path=$(realpath ${cache-file})" >> $GITHUB_OUTPUT
 
-      - name: Upload build artifacts
-        uses: actions/upload-artifact@v3.1.2
-        with:
-          name: "logs_z3_v${{ matrix.z3version }}"
-          path: ${{ steps.run_z3_and_upload.outputs.logs_path }}
+      - name: Delete old cache
+        run: |
+          echo "Fetching list of cache key"
+          cacheKeys=$(gh cache list -L 100 | cut -f 1 )
+
+          ## Setting this to not fail the workflow while deleting cache keys. 
+          set +e
+          echo "Deleting caches..."
+          for cacheKey in $cacheKeys
+          do
+              gh cache delete ${{ steps.cache.outputs.cache_id }}
+          done
+          echo "Done"
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
